name: ccomixmanager # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1.2.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: Il primo gestionale per snap in gtk e mariadb # 79 char long summary
description: |
  Il primo gestionale in gtk e mariadb per snap.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  ccomixmanager:
    source: https://github.com/numerunix/ccomixmanager/archive/refs/heads/main.zip
    # See 'snapcraft plugins'
    plugin: meson
